# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2020-02-25 13:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StuClass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_name', models.CharField(blank=True, max_length=32, null=True, verbose_name='name')),
            ],
            options={
                'verbose_name_plural': 'StudentsOfClass',
            },
        ),
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stu_name', models.CharField(blank=True, max_length=32, null=True, verbose_name='name')),
                ('stu_genders', models.IntegerField(blank=True, choices=[(0, 'girl'), (1, 'boy')], null=True, verbose_name='genders')),
            ],
            options={
                'verbose_name_plural': 'StudentsInfo',
            },
        ),
        migrations.AddField(
            model_name='stuclass',
            name='class_students',
            field=models.ManyToManyField(blank=True, to='app01.Students', verbose_name='students'),
        ),
    ]
